name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # Run checks on PR

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'  # Required for Workload Identity Federation

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Decode and Authenticate
        run: echo "${{ secrets.GCP_CREDENTIALS_B64 }}" | base64 --decode > gcp-key.json

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform Version
        run: terraform --version

