name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # Run checks on PR

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'  # Required for Workload Identity Federation

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0  # Use latest stable version

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform Changes
        run: terraform plan -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -out=tfplan

      - name: Apply Terraform Changes
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
