name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Trigger on main branch push
  pull_request:
    branches:
      - main  # Run checks on PR

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0  # Use latest stable version

      - name: Set up GCP credentials
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-credentials.json

      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file=gcp-credentials.json

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve tfplan

